Repository zeek/zeek-agent, pull requests merged in 2020-01, with the labels that each got.

#6 Fix typo in README.md
  README.md
Labels: documentation

#13 scripts: Update the release build script
  scripts/build_release.sh
Labels: enhancement

#17 CI: Add basic validation of package contents
  .github/workflows/linux.yml
  scripts/build_linux_release.sh
  scripts/check_linux_package.sh
Labels: misc

#20 Scripts: Update the Linux build script
  scripts/build_linux_release.sh
Labels: misc
